import type { AppProps } from 'next/app'
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';

import styles from 'src/styles/App.module.css';


export default function App({Component, pageProps}: AppProps) {
  return <>
    <Head>
      <title>Pokemon App</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <main className={styles.main}>
      <div className={styles.container}>
        <Component {...pageProps} />
      </div>
    </main>
  </>
}
